const fs = require('fs');
const path = require('path');

require('dotenv').config();

const constants = {
  ARETICA_ANTHROPIC_KEY:       process.env.ARETICA_ANTHROPIC_KEY       || process.env.ANTHROPIC_API_KEY    || '',
  ARETICA_ELEVENLABS_KEY:      process.env.ARETICA_ELEVENLABS_KEY      || process.env.ELEVENLABS_API_KEY   || '',
  ARETICA_ELEVENLABS_VOICE_ID: process.env.ARETICA_ELEVENLABS_VOICE_ID || process.env.ELEVENLABS_VOICE_ID  || '',
  ARETICA_SUPABASE_URL:        process.env.ARETICA_SUPABASE_URL        || process.env.SUPABASE_URL         || '',
  ARETICA_SUPABASE_ANON_KEY:   process.env.ARETICA_SUPABASE_ANON_KEY   || process.env.SUPABASE_ANON_KEY    || '',
};

const output = `// AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/inject-env.js at build time
export const BUILD_CONSTANTS = ${JSON.stringify(constants, null, 2)};
`;

fs.writeFileSync(
  path.join(__dirname, '..', 'src', 'buildConstants.ts'),
  output,
);

console.log('[inject-env] Build constants written');
console.log('[inject-env] Keys present:', Object.keys(constants).filter(k => constants[k].length > 0));
