// AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/inject-env.js at build time
export const BUILD_CONSTANTS = {
  "ARETICA_ANTHROPIC_KEY": "",
  "ARETICA_ELEVENLABS_KEY": "",
  "ARETICA_ELEVENLABS_VOICE_ID": "",
  "ARETICA_SUPABASE_URL": "",
  "ARETICA_SUPABASE_ANON_KEY": ""
};
